export const INC_QUANTITY = 'INC_QUANTITY';
export const DEC_QUANTITY = 'DEC_QUANTITY';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const SET_CARDINFO = 'SET_CARDINFO';
export const FETCH_CARDINFO_FAILED = 'FETCH_CARDINFO_FAILED';

// export const SET_CATEGORY