export const INC_QUANTITY = 'INC_QUANTITY';
export const DEC_QUANTITY = 'DEC_QUANTITY';
export const RESET_QUANTITY = 'RESET_QUANTITY';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';
export const START_SET_CATEGORIES = 'START_SET_CATEGORIES';

export const SET_CARDINFO = 'SET_CARDINFO';
export const FETCH_CARDINFO_FAILED = 'FETCH_CARDINFO_FAILED';
export const START_SET_CARDINFO = 'START_SET_CARDINFO';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';

export const PLACE_ORDER_START = 'PLACE_ORDER_START';
export const PLACE_ORDER_FAILED = 'PLACE_ORDER_FAILED';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_RESET = 'PLACE_ORDER_RESET';

export const CATEGORY_FETCH_START = 'CATEGORY_FETCH_START';
export const CATEGORY_FETCH_SET = 'CATEGORY_FETCH_SET';
export const CATEGORY_FETCH_FAIL = 'CATEGORY_FETCH_FAIL';

export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAIL = 'CANCEL_ORDER_FAIL';